build: off

skip_branch_with_pr: true

environment:
  matrix:
    - nodejs_version: "Current"

configuration: Release
platform:
  - x86
  - x64
init:
  - ps: $env:LABEL = If ($env:APPVEYOR_REPO_TAG -eq $true) { "Tag" + $env:APPVEYOR_REPO_TAG_NAME } else { "nontaglabel" }
install:
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

after_test:
  - ps: If ($env:nodejs_version -eq "Current") { npm run prebuild }

artifacts:
  - path: prebuilds
    name: $(LABEL)-win-$(PLATFORM)
    type: zip
