version: '{branch}-{build}'

build: off

skip_branch_with_pr: true

image:
  - Ubuntu2004
  - Visual Studio 2019
  - macOS-BigSur

platform:
# - x86
  - x64

for:
  -
    matrix:
      only:
        - image: Visual Studio 2019
#   init:
#     - ps: Get-Childitem -Path Env:* | Sort-Object Name
#     - ps: $env:OS
    install:
      - ps: Install-Product node Current
      - npm install
    before_build:
      - ps: if ($env:APPVEYOR_REPO_TAG -eq "false") { Exit-AppveyorBuild }
    build_script:
      - npm run prebuild
#     - npm run prebuild:ia32
    after_build:
#     - ps: Get-ChildItem -Force -Recurse .\prebuilds
      - ps: $env:ARCHIVE_NAME="$env:APPVEYOR_REPO_TAG_NAME-$env:OS-$env:PLATFORM.zip"
#     - ps: $env:ARCHIVE_NAME
      - ps: 7z a $env:ARCHIVE_NAME ./prebuilds/win32-x64
#     - ps: 7z a $env:ARCHIVE_NAME ./prebuilds/win32-x64 ./prebuilds/win32-ia32
      - ps: Push-AppveyorArtifact $env:ARCHIVE_NAME
    before_test:
      - node --version
      - npm --version
    test_script:
      - npm test
  -
    matrix:
      only:
        - image: Ubuntu2004
#   init:
#     - env
#     - nvm ls-remote
#     - uname -s
    install:
      - nvm install node
      - npm install
    before_build:
      - if [[ "$APPVEYOR_REPO_TAG" == "false" ]]; then appveyor exit; fi
    build_script:
      - npm run prebuild
    after_build:
#     - ls -lAR ./prebuilds
      - ARCHIVE_NAME="$APPVEYOR_REPO_TAG_NAME-$(uname -s)-$(uname -m).tar"
#     - echo $ARCHIVE_NAME
      - tar --create --verbose --file="$ARCHIVE_NAME" --directory "./prebuilds/" linux-x64
      - appveyor PushArtifact $ARCHIVE_NAME
    before_test:
      - node --version
      - npm --version
    test_script:
      - npm test
  -
    matrix:
      only:
        - image: macOS-BigSur
#   init:
#     - env
#     - nvm ls-remote
#     - uname -s
    install:
      - nvm install node
      - npm install
    before_build:
      - if [[ "$APPVEYOR_REPO_TAG" == "false" ]]; then appveyor exit; fi
    build_script:
      - npm run prebuild
    after_build:
#     - ls -lAR ./prebuilds
      - ARCHIVE_NAME="$APPVEYOR_REPO_TAG_NAME-$(uname -s)-$(uname -m).tar"
#     - echo $ARCHIVE_NAME
      - tar --create --verbose --file="$ARCHIVE_NAME" --directory "./prebuilds" darwin-x64
      - appveyor PushArtifact $ARCHIVE_NAME
    before_test:
      - node --version
      - npm --version
    test_script:
      - npm test

deploy:
  - provider: GitHub
    draft: false
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
    auth_token:
      secure: qwSAMLblPDtsLCl21LFbXc9E4sIaORaYHD9Hqog2ADWGecKVCrJAqnNjyVuubUOJ